FROM node:18-alpine AS build 
WORKDIR /app
COPY  package.json package-lock.json ./
RUN npm install
COPY . . 
RUN npm run build 
# ---- Étape 2 : Production --------------------------------
FROM nginx:alpine

# Copier le build dans nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copier la config nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]