# ============================================================
# nginx.conf
# Projet     : Internal Developer Platform (IDP)
# Auteur     : Doaa Ben Marzouk
# École      : ENICarthage
# ============================================================

server {
    listen 3000;
    server_name localhost;

    # ---- Fichiers React ----------------------------------
    root /usr/share/nginx/html;
    index index.html;

    # ---- React Router ------------------------------------
    # Redirige toutes les routes vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # ---- Proxy vers Backend ------------------------------
    location /api {
        proxy_pass http://backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # ---- Fichiers statiques ------------------------------
    location ~* \.(js|css|png|jpg|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # ---- Gestion erreurs ---------------------------------
    error_page 404 /index.html;
}