# ============================================================
# vars/main.yml
# Projet      : Internal Developer Platform (IDP)
# Description : Variables du rôle prepare_env
#               (les "ingrédients" utilisés par les tâches)
# ============================================================

docker_image: "{{ service_name }}:latest"
docker_context_path: "/tmp/{{ service_name }}"
k3s_binary: /usr/local/bin/k3s
kubeconfig_path: /etc/rancher/k3s/k3s.yaml
minikube_driver: docker