

# ---- Image Docker -----------------------------------------
docker_image: ""
service_name: ""
# Docker Hub


# ---- GitHub (Option 2) ------------------------------------
# Vide par défaut = Option 1 (Docker Hub)
# Fourni = Option 2 (GitHub + Buildpacks)
github_repo: ""
github_branch: ""
code_dest: "/tmp/{{ service_name }}"

# ---- Buildpacks -------------------------------------------
pack_version: "v0.40.7"                             
pack_builder: "paketobuildpacks/builder-jammy-tiny"  
pack_binary_path: "/usr/local/bin/pack"
docker_hub_username: "doua82400"               

# ---- K3s --------------------------------------------------
k3s_binary: "/usr/local/bin/k3s"
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
