# ============================================================
# hosts.yml
# Projet      : Internal Developer Platform (IDP)
# Description : Inventory — une seule machine : localhost WSL
# ============================================================

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
