# ============================================================
# application.properties
# Projet      : Internal Developer Platform (IDP)
# Auteur      : Doaa Ben Marzouk
# ============================================================

# ---- Application ------------------------------------------
spring.application.name=idp-backend
server.port=8085

# ---- MySQL ------------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/idp_db
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---- JPA --------------------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# ---- Actuator (Prometheus) --------------------------------
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.exposure.exclude=env,beans
management.health.db.ignore-routing-data-sources=true
management.endpoint.health.show-details=always

# ---- Ansible ----------------------------------------------
ansible.playbook.path=C:/Users/Doua/Downloads/internal-developer-platform/ansible/playbook.yml

# ---- Terraform --------------------------------------------
terraform.path=C:/Users/Doua/Downloads/internal-developer-platform/terraform