# ============================================================
# handlers/main.yml
# Projet      : Internal Developer Platform (IDP)
# Auteur      : Doaa Ben Marzouk
# Description : Handlers — déclenchés seulement si changement
# ============================================================

- name: restart docker
  systemd:
    name: docker
    state: restarted
  listen: "restart docker"

- name: restart k3s
  systemd:
    name: k3s
    state: restarted
  listen: "restart k3s"
