# ============================================================
# handlers/main.yml
# Projet      : Internal Developer Platform (IDP)
# Description : Actions déclenchées SEULEMENT si un changement
#               se produit dans les tâches
#               (comme un "if" conditionnel automatique)
# ============================================================

- name: Restart K3S
  systemd: 
     name: k3s
     state: restart
  listen: "restart k3s"