# ============================================================
# playbook.yml
# Projet      : Internal Developer Platform (IDP)
# Auteur      : Doaa Ben Marzouk
# École       : ENICarthage
# Description : Point d'entrée Ansible
#               Exécuté AVANT Terraform
#
# Lancement :
#   ansible-playbook playbook.yml \
#     -e "service_name=user-service" \
#     -e "github_repo=https://github.com/douabenmarzouk/user-service"
# ============================================================

- name: Préparer l'environnement de déploiement IDP
  hosts: k3s-vm
  become: true

  vars:
    service_name: "{{ service_name | default('demo-service') }}"
    github_repo: "{{ github_repo | default('https://github.com/douabenmarzouk/demo-service') }}"
    github_branch: "{{ github_branch | default('main') }}"

  roles:
    - prepare_env
